config/routes.rb
Rails.application.routes.draw do

  get 'admins/top'

  devise_for :admins
  devise_for :customers
  get 'items/index'
  namespace :customers, only: [:show, :edit, :update] do
    resources :cart_items, only: [:index, :create, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    resources :addresses, only: [:create, :destroy, :index, :edit, :update]
    resources :orders, only: [:new, :create, :index, :show ]do
      collection do
        get :confirm
      end
    end
  end
  namespace :items,only: [:index, :show] do
    resource :favorites, only: [:create, :destroy]
    resource :reviews, only: [:create, :destroy]
  end
  root "items#index"
  resources :items, only: [:show]
  
  namespace :admins do
    resources :items, only: [:create, :edit, :update, :show, :index]
    resources :orders, only: [:index, :update, :show]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update, :destroy]
  end

  get 'admins/top'
  
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses
  has_many :cart_items
  has_many :orders
  has_many :favorites
  has_many :reviews
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    validates_uniqueness_of :item_id, scope: :customer_id
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :order_details
    has_many :cart_items
    attachment :image
    enum sales_status: { soldout: 0, selling: 1}
    has_many :favorites
    has_many :reviews
    
    def favorited_by?(customer)
        favorites.where(customer_id: customer.id).exists?
    end

    def average_rate(item_id)
        reviews = Review.where(item_id: item_id).map{|review| review.rate }
        if reviews.length != 0
            average_rate_f = reviews.sum/reviews.length
        else
            average_rate_f = 0
        end
        average_rate = average_rate_f.round(1)
    end

    def review_number(item_id)
        review_number = reviews.length
    end

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details 
    enum payment_method: { credit: 0, deposit: 1 }
    enum which_address: {your_address: 0, other_addresses: 1, new_address: 2}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    
    
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def top
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
  end

  def index
  end

  def edit
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @review = Review.new
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admins/_header.html.erb
    <header>
    <div class="row bg-red">
        <div class="col-md-6">
            <p class="">Logo</p>
        </div>
        <div class="col-md-2">
            <p><%= link_to "Items", admins_items_path %></p>
        </div>
        <div class="col-md-2">
            <p><%= link_to "Genres", admins_genres_path %></p>
        </div>
        <div class="col-md-2">
            <% if customer_signed_in? %>
                <%= link_to "log out", destroy_admin_session_path, method: :delete %>
            <% end %>  
        </div>
    </div>
</header>

app/views/admins/top.html.erb
<%= render 'admins/header' %>

<h2>管理者画面top</h2>
<p>現在の注文件数は、</p><#%=  %><p>件です。</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cakers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  <footer>  
     this site is provided by daisuke shimizu in 2019. 
  </footer>
</html>