config/routes.rb
Rails.application.routes.draw do

  get 'admins/top'

  devise_for :admins
  devise_for :customers
  get 'items/index'
  namespace :customers, only: [:show, :edit, :update] do
    resources :cart_items, only: [:index, :create, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    resources :addresses, only: [:create, :destroy, :index, :edit, :update]
    resources :orders, only: [:new, :create, :index, :show ]do
      collection do
        get :confirm
      end
    end
  end
  namespace :items,only: [:index, :show] do
    resource :favorites, only: [:create, :destroy]
    resource :reviews, only: [:create, :destroy]
  end
  root "items#index"
  resources :items, only: [:show]
  
  namespace :admins do
    resources :items, only: [:create, :edit, :update, :show, :index]
    resources :orders, only: [:index, :update, :show]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update, :destroy]
  end

  get 'admins/top'
  
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :addresses
  has_many :cart_items
  has_many :orders
  has_many :favorites
  has_many :reviews
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    validates_uniqueness_of :item_id, scope: :customer_id
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :genre
    has_many :order_details
    has_many :cart_items
    attachment :image
    enum sales_status: { soldout: 0, selling: 1}
    has_many :favorites
    has_many :reviews
    
    def favorited_by?(customer)
        favorites.where(customer_id: customer.id).exists?
    end

    def average_rate(item_id)
        reviews = Review.where(item_id: item_id).map{|review| review.rate }
        if reviews.length != 0
            average_rate_f = reviews.sum/reviews.length
        else
            average_rate_f = 0
        end
        average_rate = average_rate_f.round(1)
    end

    def review_number(item_id)
        review_number = reviews.length
    end

end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customer
    has_many :order_details 
    enum payment_method: { credit: 0, deposit: 1 }
    enum which_address: {your_address: 0, other_addresses: 1, new_address: 2}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    
    
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
def index
    @item = Item.new 
    @items = Item.all
end
def edit
    @item = Item.find(params[:id])
end
def update
    
    @item = Item.find(params[:id])
    
    @item.update(item_params)
    
    
    redirect_to  admins_items_path
end


def create
    @item = Item.new(item_params)
    @item.save 
    redirect_to admins_items_path
end
def show
end

private
def item_params
    params.require(:item).permit(:name, :introduction, :price, :genre_id, :image, :sales_status)
end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def top
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
  end

  def index
  end

  def edit
  end
end

app/controllers/items/favorites_controller.rb
class Items::FavoritesController < ApplicationController
    def create
        @item =  Item.find(params[:id])
        @favorite = Favorite.new
        if not customer_signed_in?
            redirect_back(fallback_location: item_path)
        end
        @favorite.item_id = params[:id]
        @favorite.customer_id =  current_customer.id
        
        @favorite.save
    end

    def destroy
        @item =  Item.find(params[:id])
        
        @favorite = current_customer.favorites.find_by(item_id: @item.id)
        @favorite.destroy

    end

end

app/controllers/items/reviews_controller.rb
class Items::ReviewsController < ApplicationController
    def create
        review = Review.new(review_params)
        if review.save
            redirect_to item_path(review.item.id)
        else 
            render template: "item/show"
        end

    end

    def destroy

    end
    private
    def review_params
        params.require(:review).permit(:customer_id, :item_id, :rate, :title, :content)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @review = Review.new
  end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers/items_helper.rb
module Customers::ItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items/favorites_helper.rb
module Items::FavoritesHelper
end

app/helpers/items/reviews_helper.rb
module Items::ReviewsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admins/items/edit.html.erb
<%= render 'admins/header' %>
<p>商品追加</p>
<%= form_with model:@item, url: admins_item_path, method: :patch do |i| %>
    <p>name</p>
    <%= i.text_field :name %>
    <br>
    <p>intro</p>
    <%= i.text_area :introduction %>
    <br>
    <p>price</p>
    <%= i.number_field :price %>
    <br>
    <p>genre</p>
    <%= i.select :genre_id, Genre.all.map {|p| [p.title, p.id]}, :prompt => "選択してください" %>
    <br>
    <p>image</p>
    <%= i.attachment_field :image %>
    <br>
    <p>status</p>
    <%= i.select :sales_status, Item.sales_statuses.keys.to_a, {}, :prompt => "選択してください" %>
    <br>
    <p></p>
    <%= i.submit "start selling!" %>
<% end %>

app/views/admins/items/index.html.erb
<%= render 'admins/header' %>
<p>商品追加</p>
<%= form_with model:@item, url: admins_items_path, method: :post do |i| %>
    <p>name</p>
    <%= i.text_field :name %>
    <br>
    <p>intro</p>
    <%= i.text_area :introduction %>
    <br>
    <p>price</p>
    <%= i.number_field :price %>
    <br>
    <p>genre</p>
    <%= i.select :genre_id, Genre.all.map {|p| [p.title, p.id]}, :prompt => "選択してください" %>
    <br>
    <p>image</p>
    <%= i.attachment_field :image %>
    <br>
    <p></p>
    <%= i.submit "start selling!" %>
<% end %>

<% @items.each do |i| %>
<%= i.name %>
<%= i.price %>
<% end %>

app/views/items/_favorite.html.erb
<div id="favorites_buttons_<%= item.id %>">
<% if item.favorited_by?(current_customer) %>
     <%= button_to "取り消し", {:controller => "items/favorites", :action => "destroy"}, {method: :delete,params: {id: item.id},remote: true} %>
     <i class="fas fa-heart"></i>
     <%= "いいね数"+ item.favorites.count.to_s%>
<% else %>
     <%= button_to "いいね", items_favorites_path,{params: {id: item.id},remote: true} %>
     <i class="far fa-heart"></i>
     <%= "いいね数"+ item.favorites.count.to_s %>
<% end %>
</div>

app/views/items/index.html.erb
<%= render 'customers/header' %>
<h1>items/index</h1>
<% @items.each do |i| %>
<table class="table table-striped">
<%=link_to i.name , item_path(i.id)%>
<%= i.price %>
<%= i.introduction %>
<%= i.sales_status %>
</table>
<% end %>

<%= console %>

app/views/items/show.html.erb
<%= render 'customers/header' %>
<h3>アイテムの詳細</h3>
<h2><%= @item.name %></h2>
<%= attachment_image_tag @item, :image, :fill, 60, 60, fallback: "no_img.jpg" %>
<%= @item.price %>yen 
<h2>いいねする</h2>
<%= render "favorite", item: @item %>
<h2>この商品をカートにいれる</h2>
<% if customer_signed_in? %>
        <%= form_with model: @cart_item, url: customers_cart_items_path(current_customer.id), method: :post do |ci|  %>
        <%= ci.select :amount,{"1つ"=>1,"2つ"=>2,"3つ"=>3},{selected: 1},{} %>
        <%= ci.hidden_field :item_id, :value => @item.id  %>
        <%= ci.hidden_field :customer_id, :value => current_customer.id  %>
        <%= ci.submit %>
    <% end %>
<% end%>
<h2>この商品のレビューを作成</h2>
<%= form_with model: Review.new, url: items_reviews_path, method: :post do |r| %>
    <%= r.hidden_field :customer_id, :value => current_customer.id %>
    <%= r.hidden_field :item_id, :value => @item.id %>
    <%= r.label :rate %>
    <br>
    <%= r.select :rate,{1=>1,2=>2,3=>3,4=>4,5=>5} %>
    <br>
    <%= r.label :title %>
    <br>
    <%= r.text_field :title %>
    <br>
    <%= r.label :content %>
    <br>
    <%= r.text_area :content %>
    <%= r.submit %>
<% end %>
<h2>カスタマーレビュー</h2>
<%= "合計"+ @item.review_number(@item.id).to_s+"件のコメント" %>
<%= "平均評価"+ @item.average_rate(@item.id).to_s %>
<% Review.all.each do |r| %>
<table>
    <thead>
        <tr>
            <th>
                rate
            </th>
            <th>
                customer
            </th>
            <th>
                title
            </th>
            <th>
                content
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <%= r.rate.to_i %>
            </td>
            <td>
                <%= r.customer.first_name.to_s %>
            </td>
            <td>
                <%= r.title %>
            </td>
            <td>
                <%= r.content %>
            </td>
        </tr>
    </tbody>
</table>
    
<% end %>